-- Create Database
CREATE DATABASE mycustomerdata;

-- Switch to the database
use mycustomerdata;

-- checking if the table got updated or not
select * from mytable limit 5

-- 1. What is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from mytable
group by gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from mytable);

-- 3. Which are the top 5 product with the highest average review ratings?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. Compare the average Purchase amounts between standard and express shipping?
select shipping_type,
round(avg(purchase_amount),2)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5. Do subscribed customers spend more? 
--   Compare average spend and total revenue between subscribed and non-subscribed.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue, avg_spend desc;

-- 6. Which 5 product have the highest percentage of purchases with discount applied?
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. Segment customres into new, Returning, and loyal based on their total number of 
--    previous purchases, and show the count of each segment.(1=new, 2-10=Returning, above10=loyal)
with customer_type as (
select customer_id, 
       previous_purchases,
       case
           when previous_purchases = 1 then 'New'
           when previous_purchases between 2 and 10 then 'Returning'
		   else 'Loyal'
           end as customer_segment
from mytable
)

select customer_segment, 
	   count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- 8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
       item_purchased,
       count(customer_id) as total_orders,
       row_number() over(partition by category order by count(customer_id)desc) as item_rank
from mytable
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 pervious purchases) also likely to
-- subscribe?
select subscription_status,
       count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status;

-- 10. What is the revenue contribution of each age group?
select age_group, 
sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;